### ISSUE TITLE
suggestion: add link to home screen

### ISSUE THREAD

**Issue by Charles7z** [ronaldloyko/linkbox#18]
Nice start on your app! I've been using BookmarkFolder for years, would be nice to have an open source link manager.

Add link to home screen is a big bonus — I know most think that you can do that with the browser. Well, you actually can't because the browser puts whatever the website decides, which is often a PWA and not what you may want. The only workaround I've found is using a bookmark manger to create home screen links. Other than that the import/export html is the only thing needed for me to drop bookmarkfolder 😀

Nice clean simple design, BTW.

**Comment by ronaldloyko** [comment]
Thanks for the kind feedback and the suggestion!
I think that could be feasible using [this plug-in](https://github.com/NePheus/capacitor-android-shortcuts)  
Will investigate this and if it's possible I will implement this in one of the next versions.
