### ISSUE TITLE
suggestion: Arrange all the tabs

### ISSUE THREAD

**Issue by RoestVrijStaal** [ronaldloyko/linkbox#20]
**Description**

ATM it is not possible to arrange the tabs. Now are tabs ordered by their creation date, which is annoying when you've to scroll all to the right to get the right tab.

**Solution**

Create a way to arrange tabs. I think the easy and convenient way is a separate screen with a listing of tab names with the possibly to tap-hold-drag to reorder the tabs. If that's too tedious to implement, I'd recommend buttons up/down per "rule" in the listing to arrange the tab to a higher or lower sibling.

"Smart" order functions like ordering by "Tab with the lasted added link", "Tab with the most used links" require user tracking. And because the order keeps changing automatically, it presents unexpected behaviour towards the user.

**Comment by ronaldloyko** [comment]
Hi, thanks for your suggestion!
I will include this in the next major version.
