### ISSUE TITLE
BUG WebView 114 breaks dropdown functionality

### ISSUE THREAD

**Issue by backtabber** [ronaldloyko/linkbox#31]
BUG WebView 114 breaks dropdown functionality.
Dropdown boxes no longer function when touched, therefore options cannot be changed.

**Comment by cyberhardt** [comment]
also happening on my device

**Comment by Patronos** [comment]
I too have this problem. It is not possible to select anything from drop down menus. E.g. like moving bookmarks from one tab to another. Could this be investigated and fixed? Thanks a lot.
