### ISSUE TITLE
suggestion: Ability to share URL from browser's share menu

### ISSUE THREAD

**Issue by urmomsangus** [ronaldloyko/linkbox#4]
**Description**

When I try to share a URL from Firefox or Kiwi browser, Linkbox doesn't show up as an option to share the URL to.

**Solution**

Having the ability to share a URL to the app will allow quick migration to Linkbox. 

**Additional Context**

I don't know if the function would have to be added in different ways for both Chromium and Firefox based browsers to see Linkbox in the share menu.

Regardless, Linkbox is smooth and beautiful. I'm excited to see what you do with this app. It's definitely my favorite FOSS link app I've found so far, so huge thank you!

**Comment by ronaldloyko** [comment]
Thank you very much for your kind feedback and your suggestion!
This is definitely a useful feature and I will include it in the next version.
