### ISSUE TITLE
issue: Flashbang

### ISSUE THREAD

**Issue by yephny** [ronaldloyko/linkbox#5]
**Description**
Even after I selected the dark theme, the app starts with a white screen that resembles the effect of a flashbang in media.

**Reproduction Steps**
1. Launch the app.

**Expected Behavior**
The starting screen should be black.

**Environment**
- Operating System: Android 10
- Application Version: 1.0.0

**Comment by ronaldloyko** [comment]
Thanks for reporting.
Will be fixed in the upcoming version.
