### ISSUE TITLE
suggestion: Implement search button or gesture 

### ISSUE THREAD

**Issue by urmomsangus** [ronaldloyko/linkbox#8]
Currently to search requires 2 presses: three-dot menu then tap search.

It would be convenient if there was either:

- a search button near the plus sign add-link button
- or maybe a swipe up in the unused space (beside the links) gesture to open search

Just a thought. Thanks again for the app.

**Comment by NR8124** [comment]
> It would be convenient if there was either:
> 
> * a search button near the plus sign add-link button
> * or maybe a swipe up in the unused space (beside the links) gesture to open search

or else on the right top corner add settings and search **separately**

**Comment by ronaldloyko** [comment]
Thanks for your suggestions!

I would go with the variant suggested by @NR8124.
This is how it would look like:

<img alt="Dark Theme" src="https://user-images.githubusercontent.com/108372764/184254858-d764efa6-27e2-40f2-a0a6-f378e69bbb18.png" width="250">
<img alt="Light Theme" src="https://user-images.githubusercontent.com/108372764/184255001-4f58f798-1456-43a3-a713-170c39656e6a.png" width="250">
